# Generated by Django 6.0.6 on 2026-06-07 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode_mk', models.CharField(max_length=20, unique=True)),
                ('nama_mk', models.CharField(max_length=100)),
                ('sks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_kelas', models.CharField(max_length=10)),
                ('pengajar', models.ManyToManyField(limit_choices_to={'role': 'PENGAJAR'}, related_name='kelas_diajar', to=settings.AUTH_USER_MODEL)),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_kelas', to='core.matakuliah')),
            ],
        ),
        migrations.CreateModel(
            name='Pelajar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('nama_pelajar', models.CharField(max_length=150)),
                ('kelas', models.ManyToManyField(related_name='daftar_pelajar', to='core.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='SesiUjian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_ujian', models.CharField(max_length=100)),
                ('tanggal_ujian', models.DateTimeField()),
                ('dokumen_rubrik', models.FileField(blank=True, null=True, upload_to='rubrik_materi/')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_ujian', to='core.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='DokumenUjian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_gambar', models.ImageField(upload_to='lembar_ujian_raw/')),
                ('tanggal_unggah', models.DateTimeField(auto_now_add=True)),
                ('pelajar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_ujian', to='core.pelajar')),
                ('sesi_ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_terkumpul', to='core.sesiujian')),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor_soal', models.IntegerField()),
                ('pertanyaan', models.TextField()),
                ('bobot_maksimal', models.FloatField()),
                ('sesi_ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_soal', to='core.sesiujian')),
            ],
            options={
                'ordering': ['nomor_soal'],
            },
        ),
        migrations.CreateModel(
            name='ParameterRubrik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deskripsi_jawaban', models.TextField(help_text='Variasi argumen jawaban yang benar untuk acuan SBERT')),
                ('bobot_parameter', models.FloatField()),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_jawaban', to='core.soal')),
            ],
        ),
        migrations.CreateModel(
            name='JawabanUjian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teks_ocr_mentah', models.TextField(blank=True, null=True)),
                ('teks_ocr_final', models.TextField(blank=True, help_text='Teks setelah direview pengajar', null=True)),
                ('skor_ai', models.FloatField(blank=True, null=True)),
                ('catatan_rag', models.TextField(blank=True, null=True)),
                ('is_overridden', models.BooleanField(default=False)),
                ('skor_akhir', models.FloatField(blank=True, null=True)),
                ('catatan_pengajar', models.TextField(blank=True, null=True)),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_detail', to='core.dokumenujian')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soal')),
            ],
        ),
    ]
